---
name: niri-tomic-os
description: This is my personal Fedora Atomic image with Greetd, Niri and Dank Linux and Nord Theme.
base-image: ghcr.io/ublue-os/base-main
image-version: 44
modules:
  - from-file: common/greetd.yml
  - from-file: common/dms-greeter.yml
  - from-file: common/niri.yml
  - from-file: common/dms.yml
  - from-file: common/dgop.yml
  - from-file: common/dsearch.yml
