# Prefer the working Pro Audio profile and configure AMD SoundWire nodes
device.profile.priority.rules = [
  {
    matches = [
      { device.name = "alsa_card.pci-0000_c4_00.5-platform-amd_sdw" }
    ]
    actions = {
      update-props = {
        priorities = [ "pro-audio" ]
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c4_00.5-platform-amd_sdw.pro-output-0" }
    ]
    actions = {
      update-props = {
        node.description = "Headphones Jack (RT721)"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c4_00.5-platform-amd_sdw.pro-output-2" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        node.description = "Internal Speakers (TAS2783)"
        priority.session = 1100
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.pci-0000_c4_00.5-platform-amd_sdw.pro-input-3" }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
