name: build niri-tomic-os
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Custom Image and ISO
        uses: blue-build/github-action@v1.11
        with:
          recipe: "recipes/recipe.yml"
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          maximize_build_space: true
          build_iso: true

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: niri-tomic-os-iso
          path: |
            ./*.iso
            ./*.iso-sha256sum
          retention-days: 7
